ShopForEverything/Models/Pager.cs
namespace ShopForEverything.Models
{
    public class Pager
    {
        public int TotalItems { get; private set; }
        public int CurrentPage { get; private set; }
        public int PageSize { get; private set; }

        public int TotalPages { get; private set; }
        public int StartPage { get; private set; }
        public int EndPage { get; private set; }

        public Pager()
        {

        }

        public Pager(int totalItems, int page, int pageSize)
        {
            int totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            int currentPage = page;

            int startPage = currentPage - 5;
            int endPage = currentPage + 4;

            if (startPage <= 0)
            {
                endPage = endPage - (startPage - 1);
                startPage = 1;
            }

            if (endPage > totalPages)
            {
                endPage = totalPages;
                if (endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }

            TotalItems = totalItems;
            CurrentPage = currentPage;
            PageSize = pageSize;
            TotalPages = totalPages;
            StartPage = startPage;
            EndPage = endPage;
        }
    }
}

ShopForEverything/Controllers/EverythingFreeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ShopForEverything.Controllers
{
    public class EverythingFreeController : Controller
    {
        public IActionResult HomePageEverythingFree()
        {
            return View();
        }
    }
}

ShopForEverything/Controllers/ExchangeStockController.cs
using Microsoft.AspNetCore.Mvc;

namespace ShopForEverything.Controllers
{
    public class ExchangeStockController : Controller
    {
        public IActionResult HomePageExchangeStock()
        {
            return View();
        }
    }
}

ShopForEverything/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopForEverything</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopForEverything.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/f830783f12.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/sketchy.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-cart-shopping"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" asp-controller="Home" asp-action="Index">Ala-bala
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Everything" asp-action="ShowAllStocks">Everything</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="ExchangeStock" asp-action="HomePageExchangeStock">Exchange stocks</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="EverythingFree" asp-action="HomePageEverythingFree">Everything Free</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Info</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">about shop</a>
            <a class="dropdown-item" href="#">about Everything</a>
            <a class="dropdown-item" href="#">contacts</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>
      </ul>
        <partial name="_LoginPartial" />
      
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ShopForEverything - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ShopForEverything/Views/Shared/_Pager.cshtml
@model Pager


<div class="container">
    @if (Model.TotalPages > 0)
    {
        <ul class="pagination justify-content-center">

            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Everything" asp-action="ShowAllStocks" asp-route-pg="@(1)">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Everything" asp-action="ShowAllStocks" asp-route-pg="@(Model.CurrentPage - 1)">Previous</a>
                </li>
            }

            @if (Model.TotalItems >= 7)
            {
                @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
                {
                    <li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="Everything" asp-action="ShowAllStocks" asp-route-pg="@pge"> @pge </a>
                    </li>
                }

                @if (Model.CurrentPage < Model.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Everything" asp-action="ShowAllStocks" asp-route-pg="@(Model.CurrentPage + 1)">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Everything" asp-action="ShowAllStocks" asp-route-pg="@(Model.TotalPages)">Last</a>
                    </li>
                }
            }

        </ul>
    }
</div>

ShopForEverything/Views/Shared/_PagerMyStock.cshtml
@model Pager


<div class="container">
    @if (Model.TotalPages > 0)
    {
        <ul class="pagination justify-content-center">

            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Everything" asp-action="MyStocks" asp-route-pg="@(1)">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Everything" asp-action="MyStocks" asp-route-pg="@(Model.CurrentPage - 1)">Previous</a>
                </li>
            }

            @if (Model.TotalItems >= 7)
            {
                @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
                {
                    <li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="Everything" asp-action="MyStocks" asp-route-pg="@pge"> @pge </a>
                    </li>
                }

                @if (Model.CurrentPage < Model.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Everything" asp-action="MyStocks" asp-route-pg="@(Model.CurrentPage + 1)">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Everything" asp-action="MyStocks" asp-route-pg="@(Model.TotalPages)">Last</a>
                    </li>
                }
                
            }

        </ul>
    }
</div>

ShopForEverything/Views/Shared/_pagerMyFavoriteStock.cshtml
@model Pager


<div class="container">
    @if (Model.TotalPages > 0)
    {
        <ul class="pagination justify-content-center">

            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Everything" asp-action="MyFavorite" asp-route-pg="@(1)">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Everything" asp-action="MyFavorite" asp-route-pg="@(Model.CurrentPage - 1)">Previous</a>
                </li>
            }

            @if (Model.TotalItems >= 7)
            {

                @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
                {
                    <li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="Everything" asp-action="MyFavorite" asp-route-pg="@pge"> @pge </a>
                    </li>
                }

                @if (Model.CurrentPage < Model.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Everything" asp-action="MyFavorite" asp-route-pg="@(Model.CurrentPage + 1)">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Everything" asp-action="MyFavorite" asp-route-pg="@(Model.TotalPages)">Last</a>
                    </li>
                }
                
            }
        </ul>
    }
</div>